import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Mitr } from "next/font/google";
import { Sofia } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const mitr = Mitr({ weight: '400',subsets: ['latin'],display: 'swap', });
const sofia = Sofia({ weight: '400',subsets: ['latin'],display: 'swap', });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sofia.className}>{children}</body>
    </html>
  );
}
